CMAKE_MINIMUM_REQUIRED(VERSION 2.8)

PROJECT(exlibsfc CXX)

INCLUDE_DIRECTORIES(${SF_INCLUDE_DIR})

ADD_DEFINITIONS(-DDEBUG_BUILD -DUS_MODULE -DSF_TRANSPORT_NETLINK)

FILE(GLOB SF_EXAMPLESFC_SRC "${SF_PROJECT_DIR}/source/example/libsfc/*.cpp")

SET(CMAKE_EXE_LINKER_FLAGS "-Wl,-rpath,\$ORIGIN -Wl,-rpath,\$ORIGIN/../../lib/cmake")

LINK_DIRECTORIES(${SF_PROJECT_DIR}/lib/ ${SF_PROJECT_DIR}/lib/third_party/ ${SF_PROJECT_DIR}/lib/cmake)

ADD_EXECUTABLE(exlibsfc ${SF_EXAMPLESFC_SRC})

TARGET_LINK_LIBRARIES(exlibsfc core sfc transport nl-3 nl-genl-3 pthread)